name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          submodules: true  # Load submodules
          fetch-depth: 0  # Load every branch
          submodules: recursive 

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Update submodule to latest commit from source branch
        run: |
          git submodule update --init
          cd themes/hugo-book
          git fetch origin source
          git checkout source
          cd ../../
          git submodule update --remote --merge

      - name: Build Hugo site
        run: hugo --config hugo.toml -d public --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
